spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luribina/config-repo-alternative.git
          default-label: master

management:
  endpoint:
    health:
      enabled: true
