spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        default-page-size: 50

jwt:
  secret: "SS1GVUNLSU5HLUxPVkUtU1BSSU5HLUFORC1IT1ctSVQtSVMtTElURVJBTExZLU1BR0lDQUxMWS1XT1JLUy1BTkQtRkFJTFMtV0lUSC1DUllQVElELUVYQ0VQVElPTlM="
