server:
  port: 0

spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: "configserver:${config.url}"

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    log-spans: true

springdoc:
  version: '@springdoc.version@'