server:
  port: 0

spring:
  application:
    name: market-instrument-id-service
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: "configserver:${config.url}"
