global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['prometheus:9090']

  # Discover Eureka services to scrape.
  - job_name: 'eureka'

    # Scrape Eureka itself to discover new services.
    eureka_sd_configs:
      - server: http://discovery:8761/eureka

    metrics_path: '/actuator/prometheus'

  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 3s
    static_configs:
      - targets: [ 'pushgateway:9091' ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
