server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${discovery.url}

spring:
  application:
    name: trade-service
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: "configserver:${config.url}"
  data:
    web:
      pageable:
        default-page-size: 50
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
