spring:
  application:
    name: discovery
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: "configserver:${config.url}"

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    log-spans: true
